### ISSUE TITLE
Multicharts PowerLanguage compatibility

### ISSUE THREAD

**Issue by dagost2** [RiderTradingTools/easylanguage#1]
Can you support .el file extensions?

**Comment by RiderTradingTools** [comment]
@dagost2 

Currently the supported file extension for code files is :   &nbsp; **.easylanguage**

Yes, I could add the ability to recognize text files with the &nbsp; **.el** &nbsp; file extension ...  but first please confirm that is what you're requesting.

**Comment by dagost2** [comment]
Yes, that's right.  .el files are used within the Multicharts platform.  easylanguage is compatible with both Tradestation and Multicharts platforms and adding .el support would allow Multicharts users to benefit as well.

**Comment by RiderTradingTools** [comment]
@dagost2 

Please test this and it a try before I post it. 

1. Unzip the file attached here
2. Then in vsCode, in the extensions, use menu to **Install from VSIX** (see screenshot)
3. Select the _easylanguage-1.0.7.vsix_ file to import the extension
4. After vsCode restarts, attempt to open your .el files to ensure that it works 

![image](https://github.com/RiderTradingTools/easylanguage/assets/152681256/e06c86d7-7415-44a1-89e8-0cb1ed285ef0)

[easylanguage-1.0.7.zip](https://github.com/RiderTradingTools/easylanguage/files/15256590/easylanguage-1.0.7.zip)

**Comment by dagost2** [comment]
Yep that works. Awesome stuff. Thanks! 

Just noticed that it would be worthwhile including the .elf file extension that's used for functions.  So indicators and strategies are covered by the .el extension, and functions by the .elf extension. That should cover the lot.

**Comment by RiderTradingTools** [comment]
**_right on!_**  happy to hear it. 
I've added .elf too and pushed to github, and will publish the extension update v1.0.7

**Comment by RiderTradingTools** [comment]
Published RiderTradingTools.easylanguage v1.0.7

**Comment by dagost2** [comment]
Thanks you @RiderTradingTools.  Great contribution.
